Создал ветку и реализовал эндпоинты
soursager/java-filmorate pull request #3
Opened 2023-10-08 16:27 UTC by soursager

2023-10-08 17:09 UTC, soursager commented
Реализовал логику запросов эндпоинта и исправил все ошибки по валидации.

2023-10-09 15:12 UTC, Fleaman777 requested changes

2023-10-09 15:12 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/BaseController.java
> +    }
хороший подход с тем, что бы вынести общую логику в абстрактный класс, 

но я бы порекомендовал или полностью убрать этот класс или сократить его просто только до объявления в нем методов create, update, getAll

на это есть несколько причин:

1 в дальнейших спринтах логика генерации айди, валидации, обращения к бд будет реализована на уровне слоя сервис и репозиторий,
2 нарушение общепринятного бест практиса - контроллер отвечает только за логику получения запроса и отправки респонса, а вся остальная логика выполняется на уровне сервиса, так мы лучше разделяем ответственность и не складываем весь функционал в один класс

2023-10-09 15:12 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public void validate(Film data) {
хороший метод с валидацией, здорово, что он выполнен в отдельном месте, а не у дублируется эта логика во всех методах

2023-10-09 15:12 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    @NotBlank
здорово, что используешь вариацию через аннотации, это сокращает количество кода и улучшает читаемость

2023-10-09 15:12 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    void falseValidate() {
хорошо было бы в названии указать, почему именно false, т. е при каких условиях выполняется тест

аналогично в др местах

2023-10-09 15:12 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +class UserControllerTest {    UserController userController;
немного форматирование поехало 

UserController userController; - должно быть на своей строке

2023-10-09 15:12 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    }
не хватает проверки на длину описания фильма, 
и соответсвенно тестов

либо я просто пропустил эту проверку

2023-10-09 15:12 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +}
здесь аналогичный подход с тестами, из навозная должно быть понятно, что проверяет тест и при каких условиях он выполняется

2023-10-10 19:34 UTC, soursager commented
Добавил тесты, изменил абстрактный класс базового контролера, исправил недочеты

2023-10-11 12:40 UTC, Fleaman777 approved these changes

2023-10-11 12:40 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +                " стал кандидатом Коломбани.");
эту длинную строку можно было бы вынести в константу, что бы не занимала место в тест методе

2023-10-12 18:27 UTC, merged