feat: Добавить базу данных H2 и работу с ней
soursager/java-filmorate pull request #5
Opened 2023-11-20 11:16 UTC by soursager

2023-11-20 16:23 UTC, Fleaman777 requested changes

2023-11-20 16:23 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +    }
не очень хорошо, что запрос вызывается в цикле, так генерируется много обращений к БД, что будет тормозить работу приложения, лучше все это делать в одном, JOIN должен был бы в этом помочь


а вообще после того как немного разделишь этот класс согласно принципе единственной ответственности, потребность в исправлении может уйти, но тем не менее)

аналогично в других похожих местах

2023-11-20 16:23 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +    public List<Film> outputOfPopularMovies(Integer count) {
название метода должно начинаться с глагола

2023-11-20 16:23 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorage.java
> +    }
аналогично тому, что описывал выше, 
только здесь, не стоит обновлять БД в цикле, это будет еще тяжелее чем просто доставать значения, 
для обновления в одном запросе можно использовать  jdbcTemplate.batchUpdate(.)

абстрактный пример мог бы выглядеть так 

film.getGenres().forEach(g -> {String sqlQuery = "INSERT INTO genre(film_id, genre_id) VALUES (?, ?)";
            jdbcTemplate.update(sqlQuery,
                    film.getId(),
                    g.getId());
        });
    }

2023-11-20 16:23 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/filmorate/storage/db/FilmDbStorageTest.java
> +                .build();
одинаковые объекты хорошо бы вынести в метод с аннотацией BeforeEach или в общие вспомогательные методы

2023-11-21 21:04 UTC, soursager commented
Изменил логику обращение к базе в DAO фильмов, убрал лишние зависимости и проверки. Исправил недочеты и слегка поправил стиль)

2023-11-22 13:37 UTC, Fleaman777 approved these changes

2023-11-28 16:37 UTC, merged